### ISSUE TITLE
No order information for 2 species

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-scheldt-checklist#1]
For the following species, the field for `order`  in the [raw dataset](https://docs.google.com/spreadsheets/d/1V_rQhyz_AjszobCMxBe-xFWI3kUNLrYzMeqyUNt3Vc4/edit#gid=0) is empty:
- `Potamopyrgus antipodarum (J.E. Gray, 1843)`
- `Physella acuta`

-> Is this OK?

**Comment by peterdesmet** [comment]
I would complete the rank to species

**Comment by LienReyserhove** [comment]
stupid mistake, `rank` in my original message should be `order` :-s I corrected this

**Comment by FrankINBO** [comment]
Order info:

Potamopyrgus antipodarum --> Littorinimorpha
Physella acuta --> Basommatophora

**Comment by LienReyserhove** [comment]
Thank you, I integrated this accordingly
