### ISSUE TITLE
No genus information for 1 species

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-scheldt-checklist#2]
For the following species, the field for `genus`  in the [raw dataset](https://docs.google.com/spreadsheets/d/1V_rQhyz_AjszobCMxBe-xFWI3kUNLrYzMeqyUNt3Vc4/edit#gid=0) is empty:
- `Tasserkidrilus near americanus`

-> Is this OK?

**Comment by peterdesmet** [comment]
Maybe better `Tasserkidrilus cf. americanus`, but it is somewhat odd to have this on a checklist though.

**Comment by LienReyserhove** [comment]
Issue solved, `genus` is now `Tasserkidrilus`
