### ISSUE TITLE
include regional distributions in distribution extension

### ISSUE THREAD

**Issue by timadriaens** [trias-project/alien-scheldt-checklist#4]
All records should be duplicated with `locality = Flanders` as the Scheldt estuary is fully located in the Flemish region. This is needed for the [checklist-based indicators](https://trias-project.github.io/indicators/) (which are at the level of the regions). 

`occurrenceStatus `, `establishmentMeans `, `eventDate` should remain the same for every record.

**Comment by LienReyserhove** [comment]
@timadriaens I think we should do this duplication in the R script, not in the raw dataset. Duplicating all records in the raw dataset will make it less readable and more complex. In the raw dataset, the location can be set to `Flanders`.

**Comment by timadriaens** [comment]
ok with setting location in the raw dataset on Flanders of course, so long as these records also end up in GRIIS Belgium through the pipeline we're all good.

**Comment by peterdesmet** [comment]
So no duplication would take place (neither script or dataset)?

**Comment by timadriaens** [comment]
If we have all of the records like this, they should end up on GRIIS Belgium right?

location | country code | occurrence status
-- | -- | --
Flanders | BE | present

**Comment by peterdesmet** [comment]
Yes
