### ISSUE TITLE
"pathway of introduction" to be replaced with "pathway" in description

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-scheldt-checklist#7]
As found in https://github.com/trias-project/unified-checklist/issues/68 and similar to https://github.com/trias-project/alien-herpetofauna-belgium/issues/15, pathway information should have `type = "pathway"` in description instead of `pathway of introduction`. This is the name used in the vast majority of checklists published within TrIAS and used for generating the unified checklist. Problem is in [dwc_mapping.Rmd#L601](https://github.com/trias-project/alien-scheldt-checklist/blob/master/src/dwc_mapping.Rmd#L601).

This can be solved by modifying it with:
```r
pathway %<>% mutate(type = "pathway")
```

**Comment by LienReyserhove** [comment]
see #10
